WIP: Update Postgresql dependency (Compatibility with nodejs > 14.0)
thenativeweb/wolkenkit-eventstore pull request #20
Opened 2021-10-29 18:33 UTC by kapitok

wokenkit-eventstore does not support of postgresql database with nodejs 14

Tested: node 14.16, postgresql 12.0

More discussion here:
https://github.com/brianc/node-postgres/issues/2069

2021-11-03 08:22 UTC, kapitok commented
Issue: https://github.com/thenativeweb/wolkenkit-eventstore/issues/21

2021-11-04 10:08 UTC, goloroden requested changes
Hey @kapitok 👋 

Thanks the PR, and sorry for the somewhat delayed reply…

I have reviewed your changes, and left a few comments. Could you please have a look at them?

Cheers,


Golo


PS: And, if you want to, please feel free to add yourself to the list of contributors in the `package.json` file.

2021-11-04 10:08 UTC, goloroden commented on package.json
> +  "version": "2.7.1",
Could you please remove this line, as increasing the version number is done by our publishing process.

2021-11-04 10:08 UTC, goloroden commented on package.json
> +    "pg": "^8.7.1",
Could you please remove the `^` sign, as we prefer to not use this?

2021-11-05 15:22 UTC, kapitok commented
@goloroden Hey, thanks for reviewing the pull request :+1: . I fixed the PR according to your comments

2021-11-06 12:54 UTC, goloroden approved these changes

2021-11-06 12:54 UTC, merged

2021-11-09 10:00 UTC, kapitok commented
@goloroden Could You, please, consider releasing a new version of the npm package?

2021-11-12 07:22 UTC, goloroden commented
Version 2.6.2 is on npm 🎉

2021-11-12 09:25 UTC, kapitok commented
> Version 2.6.2 is on npm tada

@goloroden thanks, now it works perfectly with postgres